In [142]:
### Implement the 8-puzzle game for bfs, dfs, and a-star
import numpy as np
# from resource import ru_maxrss
import sys
from random import shuffle

In [143]:
# Initialize random board
initState = list(range(9))
shuffle(initState)
print(initState)

[1, 3, 0, 8, 5, 2, 7, 6, 4]


In [173]:
## Initialize random board and check if solvable. If not, randomize again.
goalState = [0,1,2,3,4,5,6,7,8]
initState = list(range(9))
shuffle(initState)
if initState == goalState:
    shuffle(initState)

count = 0
def InversionsCount(x):
    global count
    midsection = round(len(x) / 2)
    leftArray = x[:midsection]
    rightArray = x[midsection:]
    if len(x) > 1:
        InversionsCount(leftArray)
        InversionsCount(rightArray)
        i, j = 0, 0
        a = leftArray; b = rightArray
        for k in range(len(a) + len(b) + 1):
            if a[i] <= b[j]:
                x[k] = a[i]
                i += 1
                if i == len(a) and j != len(b):
                    while j != len(b):
                        k +=1
                        x[k] = b[j]
                        j += 1
                    break
            elif a[i] > b[j]:
                x[k] = b[j]
                count += (len(a) - i)
                j += 1
                if j == len(b) and i != len(a):
                    while i != len(a):
                        k+= 1
                        x[k] = a[i]
                        i += 1                    
                    break   


InversionsCount(initState[:])
while count%2 != 0:
    shuffle(initState)
    if initState == goalState:
        shuffle(initState)
    InversionsCount(initState)
    
print("Initial board:")
print(initState)
blank = initState.index(0)
print('Goal state:')
print(goalState)
print('Initial board as matrix:')
print(np.array(initState).reshape(3,3))
print('Index location of blank space:')
print(blank)

Initial board:
[4, 8, 2, 1, 3, 7, 6, 0, 5]
Goal state:
[0, 1, 2, 3, 4, 5, 6, 7, 8]
Initial board as matrix:
[[4 8 2]
 [1 3 7]
 [6 0 5]]
Index location of blank space:
7


In [152]:
# method = sys.argv[1]
# initState = np.array(sys.argv[2]).reshape(3,3)
# goalState = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)

# method = 'bfs'
# initState = [1,5,2,3,4,0,6,7,8]
# goalState = [0,1,2,3,4,5,6,7,8]
# initState = np.array(initList).reshape(3,3)
# blank = np.argwhere(initState==0).tolist()

In [ ]:
### Move the blank to a new state

def up(state):
#  blank moves 3 steps left
    moveBlank = state[:]
    i = moveBlank.index(0)
    moveBlank[i], moveBlank[i-3] = moveBlank[i-3], moveBlank[i]
    return moveBlank

def down(state):
#  blank moves 3 steps right
    moveBlank = state[:]
    i = moveBlank.index(0)
    moveBlank[i], moveBlank[i+3] = moveBlank[i+3], moveBlank[i]
    return moveBlank

def left(state):
#  blank moves 1 step left
    moveBlank = state[:]
    i = moveBlank.index(0)
    moveBlank[i], moveBlank[i-1] = moveBlank[i-1], moveBlank[i]
    return moveBlank

def right(state):
#  blank moves 1 step right
    moveBlank = state[:]
    i = moveBlank.index(0)
    moveBlank[i], moveBlank[i+1] = moveBlank[i+1], moveBlank[i]
    return moveBlank

print(initState)
changeState = initState
print(down(changeState))
print(initState)

In [ ]:
### Identify adjacent neighbors of the blank
def findNeighbors(state):
    neighborState = {}
    i = state.index(0)
    #Check edges
    if i not in (0,3,6): #left side
        neighborState['left'] = left(state)
    if i not in (0,1,2): #up
        neighborState['up'] = up(state)
    if i not in (2,5,8): #right
        neighborState['right'] = right(state)
    if i not in (6,7,8): #down
        neighborState['down'] = down(state)
    return neighborState

## Test
print('Initial board state: ')
print(initState)
print('location of blank space: ')
print(blank)
print('neighbors of blank space: ')
print(findNeighbors(initState))

In [ ]:
def bfs(initState):
    print("Initial state...")
    print(initState)
    init = initState[:]
    frontier = [init]
    explored = []
    neighbors = []
    path_to_goal = []
    cost_of_path = 0
    while len(frontier) > 0:
        state = frontier[0] 
        frontier.pop(0)
        explored.append(state)
        if state == goalState:
            return "Success!" + \
                    "final State: " + state + \
                    "path_to_goal: " + path_to_goal + \
                    "cost_of_path: " + cost_of_path
        for path, neighbor in findNeighbors(state).items():
            if neighbor not in frontier and neighbor not in explored:
                frontier.append(neighbor)
                neighbors.append(path)
        path_to_goal.append(neighbors[0])
        neighbors.pop(0)
        cost_of_path += 1
        print('path:')
        print(path_to_goal)
        print('cost of path:')
        print(cost_of_path)
    return 'Failure'
 

In [ ]:
bfs(initState)

In [ ]:
print("Initial state...")
print(initState)
init = initState[:]
print("Frontier...")
frontier = [init]
print(frontier)
print('Length of Frontier...')
print(len(frontier))
explored = []
neighbors = []
path_to_goal = []
cost_of_path = 0
state = frontier[0]
frontier.pop(0)
print('Updated length of Frontier...')
print(len(frontier))
print('State...')
print(state)
explored.append(state)
print('Explored...')
print(explored)
print('Find Neighbors...')
for path, neighbor in findNeighbors(state).items():
    if neighbor not in frontier and neighbor not in explored:
        frontier.append(neighbor)
        neighbors.append(path)
path_to_goal.append(neighbors[0])
cost_of_path += 1
print('Updated frontier...')
print(frontier)
print('neighbors...')
print(neighbors)
print('Updated length of Frontier...')
print(len(frontier))
print('path...')
print(path_to_goal)
print('cost of path...')
print(cost_of_path)
print('ROUND 2!')
state = frontier[0]
frontier.pop(0)
neighbors.pop(0)
print('Updated length of Frontier...')
print(len(frontier))
print('State...')
print(state)
explored.append(state)
print('Explored...')
print(explored)
print('Find Neighbors...')
for path, neighbor in findNeighbors(state).items():
    if neighbor not in frontier and neighbor not in explored:
        frontier.append(neighbor)
        neighbors.append(path)
path_to_goal.append(neighbors[0])
cost_of_path += 1
print('Updated frontier...')
print(frontier)
print('neighbors...')
print(neighbors)
print('Updated length of Frontier...')
print(len(frontier))
print('path...')
print(path_to_goal)
print('cost of path...')
print(cost_of_path)
print('ROUND 3!')
state = frontier[0]
frontier.pop(0)
neighbors.pop(0)
print('Updated length of Frontier...')
print(len(frontier))
print('State...')
print(state)
explored.append(state)
print('Explored...')
print(explored)
print('Find Neighbors...')
for path, neighbor in findNeighbors(state).items():
    if neighbor not in frontier and neighbor not in explored:
        frontier.append(neighbor)
        neighbors.append(path)
path_to_goal.append(neighbors[0])
cost_of_path += 1
print('Updated frontier...')
print(frontier)
print('neighbors...')
print(neighbors)
print('Updated length of Frontier...')
print(len(frontier))
print('path...')
print(path_to_goal)
print('cost of path...')
print(cost_of_path)

In [ ]:
testlist = [0,1,2,3,4,5]
x = testlist[0]
print(x)
testlist.pop(0)
print(testlist)

In [ ]:
print(state)

In [ ]:
state == goalState

In [ ]:
test = [[0,1,2,3,4,5,6,7,8],[1,2,3,7,4,0,6,5,8]]
teststate = test[0]
teststate == goalState

In [ ]:
int getInvCount(int arr[])
{
    int inv_count = 0;
    for (int i = 0; i < 9 - 1; i++)
        for (int j = i+1; j < 9; j++)
             // Value 0 is used for empty space
             if (arr[j] && arr[i] &&  arr[i] > arr[j])
                  inv_count++;
    return inv_count;
}

bool isSolvable(int puzzle[3][3])
{
    // Count inversions in given 8 puzzle
    int invCount = getInvCount((int *)puzzle);

    // return true if inversion count is even.
    return (invCount%2 == 0);
}