In [4]:
### Implement the 8-puzzle game for bfs, dfs, and a-star
import numpy as np
# from resource import ru_maxrss
import sys

In [65]:
# method = sys.argv[0]
# initState = np.array(sys.argv[1]).reshape(3,3)
# goalState = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)

method = 'bfs'
initState = [1,5,2,3,4,0,6,7,8]
goalState = [0,1,2,3,4,5,6,7,8]
# initState = np.array(initList).reshape(3,3)
# blank = np.argwhere(initState==0).tolist()
blank = initState.index(0)
print(initState)
print(goalState)
print(np.array(initState).reshape(3,3))
print(blank)

[1, 5, 2, 3, 4, 0, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[[1 5 2]
 [3 4 0]
 [6 7 8]]
5


In [66]:
### Identify adjacent neighbors of the blank
def findNeighbors(state):
    neighborState = {}
    i = state.index(0)
    #Check edges
    if i not in (0,3,6): #left side
        neighborState['left'] = left(state)
    if i not in (0,1,2): #up
        neighborState['up'] = up(state)
    if i not in (2,5,8): #right
        neighborState['right'] = right(state)
    if i not in (6,7,8): #down
        neighborState['down'] = down(state)
    return neighborState

## Test
print('original board state: ')
print(initState)
print('location of blank space: ')
print(blank)
print('neighbors of blank space: ')
print(findNeighbors(initState))

original board state: 
[1, 5, 2, 3, 4, 0, 6, 7, 8]
location of blank space: 
5
neighbors of blank space: 
{'down': [1, 5, 2, 3, 0, 4, 6, 7, 8], 'up': [1, 5, 2, 3, 0, 4, 6, 7, 8], 'left': [1, 5, 2, 3, 0, 4, 6, 7, 8]}


In [46]:
### Move the blank to a new state

def up(state):
#  blank moves 3 steps left
    i = state.index(0)
    state[i], state[i-3] = state[i-3], state[i]
    return state

def down(state):
#  blank moves 3 steps right
    i = state.index(0)
    state[i], state[i+3] = state[i+3], state[i]
    return state

def left(state):
#  blank moves 1 step left
    i = state.index(0)
    state[i], state[i-1] = state[i-1], state[i]
    return state

def right(state):
#  blank moves 1 step right
    i = state.index(0)
    state[i], state[i+1] = state[i+1], state[i]
    return state

print(initState)
down(initState)

[1, 5, 2, 3, 4, 0, 6, 7, 8]


[1, 5, 2, 3, 4, 8, 6, 7, 0]

In [58]:
def bfs(initState):
    frontier = [initState]
    explored = []
    path_to_goal = []
    cost_of_path = 0
    while len(frontier) > 0:
        state = frontier[0]
        explored.append(state)
        if state == goalState:
            return "Success!" + \
                    "initial State: " + initState + \
                    "final State: " + state + \
                    "path_to_goal: " + path_to_goal + \
                    "cost_of_path: " + cost_of_path
        for neighbor in findNeighbors(state).values:
            if neighbor not in frontier and neighbor not in explored:
                frontier.append(neighbor)
    return 'Failure'
 

In [59]:
bfs(initState)

TypeError: 'builtin_function_or_method' object is not iterable